Import('env')

e = env.Clone()
e['ENV']['PYTHONPATH'] = 'lib'
e['ENV']['PATH'] = 'bin:' + e['ENV']['PATH']

# Custom builder to run unit tests:
def builder_unit_test(target, source, env):
    opts = ""
    if env.get('html_coverage', None):
        opts = '--html_coverage=%s ' % env['html_coverage']
    app = "python %s %s-v > /dev/null" % (source[0], opts)
    if e.Execute(app) == 0:
        file(str(target[0]), 'w').write('PASSED\n')
    else:
        print "unit tests FAILED"
        return 1
e.Append(BUILDERS = {'Test': Builder(action=builder_unit_test)})

# Always run our unit test:
test = e.Test("test.passed", ["run-all-tests.py"])
e.Alias("test", test)
e.AlwaysBuild("test.passed")
