#!/bin/bash
# 1) pdbfile 2) chaind 3)startres 4)endres

awk 'BEGIN{FS=""}(($1$2$3$4=="ATOM"||$1$2$3$4=="HETA")&&$22=="'${2}'"){print $23$24$25$26" "$0}' $1 |\
awk '($1>='${3}'&&$1<='${4}'){print $0}' |\
awk 'BEGIN{FS=""}{for(a=6;a<=NF;a++){printf $a;if(a==NF){printf "\n"}}}'  | sed "s/HSD/HIS/g" | sed "s/HSP/HIS/g" 
