Import('env')
import os

pyso = env.LoadableModule('#/lib/allosmod/modeller/_truncated_gaussian',
                          ['truncated_gaussian.i', 'truncated_gaussian.c'],
                          SWIGFLAGS="-python -noproxy",
                          SHLIBPREFIX="")

i = env.Install(os.path.join(env['pythondir'], 'allosmod', 'modeller'), pyso)
env.Alias('install', i)

Return('pyso')
